const RATINGS = {
  maxSharpness: {
    1:  { label: 'Extreme Low', tier: 'low'  },
    2:  { label: 'Very Low',    tier: 'low'  },
    3:  { label: 'Low',         tier: 'low'  },
    4:  { label: 'Average',     tier: 'med'  },
    5:  { label: 'Moderate',    tier: 'med'  },
    6:  { label: 'Good',        tier: 'med'  },
    7:  { label: 'High',        tier: 'med' },
    8:  { label: 'Very High',   tier: 'high' },
    9:  { label: 'Excellent',   tier: 'high' },
    10: { label: 'Extreme',     tier: 'high' },
  },
  corrosionRes: {
    1:  { label: 'Extreme Low', tier: 'low'  },
    2:  { label: 'Very Low',    tier: 'low'  },
    3:  { label: 'Low',         tier: 'low'  },
    4:  { label: 'Average',     tier: 'med'  },
    5:  { label: 'Moderate',    tier: 'med'  },
    6:  { label: 'Good',        tier: 'med'  },
    7:  { label: 'High',        tier: 'med' },
    8:  { label: 'Very High',   tier: 'high' },
    9:  { label: 'Excellent',   tier: 'high' },
    10: { label: 'Extreme',     tier: 'high' },
  },
  edgeRetention: {
    1:  { label: 'Extreme Low', tier: 'low'  },
    2:  { label: 'Very Low',    tier: 'low'  },
    3:  { label: 'Low',         tier: 'low'  },
    4:  { label: 'Average',     tier: 'med'  },
    5:  { label: 'Moderate',    tier: 'med'  },
    6:  { label: 'Good',        tier: 'med'  },
    7:  { label: 'High',        tier: 'med' },
    8:  { label: 'Very High',   tier: 'high' },
    9:  { label: 'Excellent',   tier: 'high' },
    10: { label: 'Extreme',     tier: 'high' },
  },
  toughness: {
    1:  { label: 'Extreme Low', tier: 'low'  },
    2:  { label: 'Very Low',    tier: 'low'  },
    3:  { label: 'Low',         tier: 'low'  },
    4:  { label: 'Average',     tier: 'med'  },
    5:  { label: 'Moderate',    tier: 'med'  },
    6:  { label: 'Good',        tier: 'med'  },
    7:  { label: 'High',        tier: 'med' },
    8:  { label: 'Very High',   tier: 'high' },
    9:  { label: 'Excellent',   tier: 'high' },
    10: { label: 'Extreme',     tier: 'high' },
  },
  easeOfSharp: {
    1:  { label: 'Near-Impossible', tier: 'low'  },
    2:  { label: 'Very Difficult',  tier: 'low'  },
    3:  { label: 'Difficult',       tier: 'low'  },
    4:  { label: 'Med-Difficult',   tier: 'med'  },
    5:  { label: 'Demanding',       tier: 'med'  },
    6:  { label: 'Moderate',        tier: 'med'  },
    7:  { label: 'Fair',            tier: 'med'  },
    8:  { label: 'Easy',            tier: 'high' },
    9:  { label: 'Very Easy',       tier: 'high' },
    10: { label: 'Effortless',      tier: 'high' },
  },
  relativeCost: {
    1:  { label: 'Astronomical', tier: 'low' },
    2:  { label: 'Very High',    tier: 'low' },
    3:  { label: 'High',         tier: 'low' },
    4:  { label: 'Premium',      tier: 'med'  },
    5:  { label: 'Moderate',     tier: 'med'  },
    6:  { label: 'Average',      tier: 'high'  },
    7:  { label: 'Low',          tier: 'high'  },
    8:  { label: 'Budget',       tier: 'high'  },
  },
  lifespan: {
    1:  { label: 'Very Short', tier: 'low'  },
    2:  { label: 'Moderate',   tier: 'med'  },
    3:  { label: 'Long',       tier: 'med'  },
    4:  { label: 'Very Long',  tier: 'high' },
  },
};

export function getRating(prop, val) {
  return RATINGS[prop][val];
}
